/*
1 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App {
    public static void main(String[] args) {
      java.util.Scanner keyboard = new java.util.Scanner(System.in);
       
       System.out.print("번호? ");
       int a = keyboard.nextInt();   
    
       keyboard.nextLine();

       System.out.print("수업명? ");
       String b = keyboard.nextLine();
       
       System.out.println("수업내용? ");
       String c = keyboard.nextLine();
       
       System.out.println("시작일: ");
       String d = keyboard.nextLine();
       
       System.out.println("종료일: ");
       String e = keyboard.nextLine();
       
       System.out.println("총수업시간: ");
       String f = keyboard.nextLine();
       
       System.out.println("일수업시간: ");
       int g = keyboard.nextInt();
       
       keyboard.nextLine();
       
       
       System.out.printf("번호: %d\n", a);
       System.out.printf("수업명? %s\n", b);
       System.out.printf("수업내용? %s\n", c);
       System.out.printf("기간: %s ~ %s\n", d, e );
       System.out.printf("총수업시간: %s시간\n", f);
       System.out.printf("일수업시간: %d시간\n", g);
       
       keyboard.close();


    }
}
