/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App3 {
 public static void main (String[]agr) {
   java.util.Scanner keyboard = new java.util.Scanner(System.in);
   java.util.Date today = new java.util.Date();
   
   System.out.println("번호 : ");
   int number = keyboard.nextInt();
   
   keyboard.nextLine();
   
   System.out.println("내용 : ");
   String text = keyboard.nextLine();
   
  int a = 0;
   System.out.printf("번호 : %d\n", number);
   System.out.printf("내용 : %s\n", text);
   System.out.printf("작성일 : %1$tY-%1$tm-%1$td\n", today);
   System.out.printf("조회수: %d\n", a);
   
   keyboard.close();


   
  
    }
}
